---
- hosts: all
  become: yes

  tasks:

    - name: create docker image using war file
      command: docker build -t simple-devops-image:latest .
      args:
        chdir: /opt/docker

    - name: create tag to image
      command: docker tag simple-devops-image akshaymore5233/simple-devops-image

    - name: push image on to dockerhub
      command: docker push akshaymore5233/simple-devops-image
      
    - name: remove web dir contents
      file: path='/home/mydata/web/{{ item }}' state=absent
      with_fileglob:
    - /home/mydata/web/*

    
